# Generated by Django 4.1.7 on 2023-03-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='c_password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
